### ISSUE TITLE
在内容比较少的时候，滚动可能会触发意外的getList请求

### ISSUE THREAD

**Issue by csthenry** [androidmumo/bing#2]
```
https://bing.bytecho.net/#/pc/detail?id=1
```
将此页面滚动到底部，从控制台可发现有异常GET请求：
```
https://api.bytecho.net/bing/getList?pageSize=9&currentPage=1.1111111111111112
```
![image](https://github.com/androidmumo/bing/assets/32993468/4025da29-2da6-4d36-84f6-e8f667deb658)

甚至currentPage是浮点数，导致主页出现重复的图片：
![image](https://github.com/androidmumo/bing/assets/32993468/9fe6a8dd-0964-44c7-a47b-e4a90448a62e)

**Comment by androidmumo** [comment]
感谢反馈，将在近期修复。

**Comment by androidmumo** [comment]
该问题已在此次提交中修复:
https://github.com/androidmumo/bing/commit/86cfe20362e8a280b6e936965b1473f5767601af
