### ISSUE TITLE
支持docker部署

### ISSUE THREAD

**Issue by androidmumo** [androidmumo/bing#3]
前后端代码将会合并入此仓库，支持统一使用docker部署。

**Comment by wujinpai** [comment]
> 前后端代码将会合并入此仓库，支持统一使用docker部署。
> 
> 这是一个轻量级的项目，用MySQl这类仓库会让配置繁琐，同时项目中没有复杂的数据交互。故初个支持docker的版本会使用SQLite替代目前的数据库。为了应对可能存在的性能问题（几乎没有），后续的版本中MySQl可能会成为可选项。

什么时候上线docker

**Comment by androidmumo** [comment]
> > 前后端代码将会合并入此仓库，支持统一使用docker部署。
> > 这是一个轻量级的项目，用MySQl这类仓库会让配置繁琐，同时项目中没有复杂的数据交互。故初个支持docker的版本会使用SQLite替代目前的数据库。为了应对可能存在的性能问题（几乎没有），后续的版本中MySQl可能会成为可选项。
> 
> 什么时候上线docker

已经在开发了，最快明天会有测试版，正式版下周发布。
