### ISSUE TITLE
Docker版本出现数据库安装失败

### ISSUE THREAD

**Issue by a12110** [androidmumo/bing#30]
在androidmumo/bing:v1.1.1 版本中出现了 #27 描述的故障，请求作者更新一下docker的镜像。

**Comment by aa12110** [comment]
附上部署日志
![image](https://github.com/androidmumo/bing/assets/121783294/ad40df86-a03c-4161-b11e-f26d7c0dea67)

**Comment by a12110** [comment]
补充部署输出信息
![image](https://github.com/androidmumo/bing/assets/121783294/5cc829ab-17ff-466b-8040-5951d6dca91b)

**Comment by androidmumo** [comment]
是更新还是全新安装？

**Comment by androidmumo** [comment]
你好，经测试，此问题无法复现。请尝试删除所有数据后重新安装
